title: "Blog Notes"
email: "jhoanseb1992@gmail.com"
author: "Johan Suarez"
description: "Blog about Technology"
#baseurl: "Mynotes" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-153097760-1
social_links:
  twitter: "jadry92"
  github: "jadry92"
  linkedin: "johan-sebastian-suarez-largo-a9980499"
  instagram: "jadry92"

logo: "assets/img/basics/logo-v2.jpg"
# Build settings
markdown: "kramdown"
theme: "jekyll-theme-minimal"
plugins:
  - jemoji
