# SITE CONFIGURATION
baseurl: ""
url: "https://blognotes.dev"

# THEME-SPECIFIC CONFIGURATION
title: "BlogNotes.Dev"
email: "johan@blognotes.dev"
author: "Johan Suarez Largo"
description: "This site contain all the notes, tutorials and ideas that I have while I create a career in tech industry."
avatar: "assets/img/basics/favicon.jpeg"                         # Empty for no avatar in navbar
favicon: "assets/img/basics/favicon.jpeg"

logo: "assets/img/basics/logo-v2.jpg"

# Header and footer text
header_text: "The perfect blog about technology"  # Change Blog header text
header_description: "This site contain all the notes, tutorials and ideas that I have while I create a career in tech industry."  # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: "Write by <a href='/about'>Johan Suarez Largo</a> using <a href='https://github.com/sylhare/Type-on-Strap'>Type-on-Strap</a>"

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: "UA-153097760-1"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons: true                                     # In _data/social.yml
authors: true                                               # In _data/authors.yml
language: true                                              # In _data/language.yml

# PAGINATION
paginate: 15
paginate_path: "page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed
plugins: ["jemoji", jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]
